### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by edhilgendorf** [springjools/ombiBot#1]
Hi, I got this working perfectly with my bot, but getting:
ERROR: Unable to request movie: -220187420
when requesting in a group. Do groups work, or planned? Any idea what this error number is? Thank you, this is a great project.

**Comment by springjools** [comment]
It's difficult to tell because I chose to handle all exceptions from that function. But it's probably and incorrect chat_id. 

I didn't plan to include groups but it would probably not be hard to implement, provided that telegram allows bots to chat with groups. I'm not so sure they do. I can investigate but I think you have to call the bot by chatting to it and give the /start command. That's how it gets your chat id that it replies to.

**Comment by edhilgendorf** [comment]
Hi, I have a couple other bots that work well in groups, I'm sure this would. I'd love to help if there's anything I can do. Thanks for the project!

**Comment by springjools** [comment]
The error number is the group id, which does not have a username related to ombi. I can work out who sent the message in the group and have the boot use that user id to make requests. 

Or would it be better to use the group id for requests, and for example have all requests made by a user called guest or anonymous or something?

The thing is that it's only when your want to get the movie that the username is checked, the browsing for available movies happens without any relation to ombi user. One other alternative would also be to make all requests using an admin, overriding all approvals etc.

**Comment by springjools** [comment]
Should be fixed in https://github.com/springjools/ombiBot/commit/b6b31dcf9ae910edda3153b39459d63445637e09 

Report if there are any issues. I'm not able to test this with new telegram users, as I only have my own phone and gf:s.
